### ISSUE TITLE
authentication failure [...] msg=path "/run/proxmox-backup/shmem" is not on tmpfs

### ISSUE THREAD

**Issue by fila612** [ayufan/pve-backup-server-dockerfiles#16]
Hi,

I've tried to install the latest docker image to my Synology via Portainer.
there were 4 Folders created on the host system and mapped into docker volumes:
![Bildschirmfoto 2022-02-13 um 10 47 12](https://user-images.githubusercontent.com/29542374/153747622-7913cb8d-39e2-469d-a775-a72d59a38376.png)

These 4 volumes are created with following options (in Portainer called "drive options":
![Bildschirmfoto 2022-02-13 um 10 48 57](https://user-images.githubusercontent.com/29542374/153747666-efec14d5-dfe5-42b5-a5cf-e07724dc3b5c.png)

after start the container, logs seems to be fine and data were created in the folders.

But, the login (admin/pbspbs) is not working:
in PBS2/logs/api I found a file "auth.log" including this:
`2022-02-13T09:39:05+00:00: authentication failure; rhost=[::ffff:172.17.0.1]:52784 user=admin@pbs msg=path "/run/proxmox-backup/shmem" is not on tmpfs`

I think there is something wrong what I did, but I'm not sure what.
Also I checked the tmpfs inside the container:
`root@79c0806a31ab:/# df -h
Filesystem              Size  Used Avail Use% Mounted on
/dev/mapper/cachedev_2  5.3T  3.4T  1.9T  65% /
tmpfs                    64M     0   64M   0% /dev
tmpfs                   5.8G     0  5.8G   0% /sys/fs/cgroup
shm                      64M     0   64M   0% /dev/shm
/dev/mapper/cachedev_2  5.3T  3.4T  1.9T  65% /backups
/dev/mapper/cachedev_2  5.3T  3.4T  1.9T  65% /etc/proxmox-backup
/dev/mapper/cachedev_2  5.3T  3.4T  1.9T  65% /etc/hosts
tmpfs                   5.8G     0  5.8G   0% /proc/acpi
tmpfs                   5.8G     0  5.8G   0% /proc/scsi
tmpfs                   5.8G     0  5.8G   0% /sys/firmware`

any suggestions how to handle this?

**Comment by ayufan** [comment]
@fila612 Synology uses pretty outdated linux kernel: https://github.com/ayufan/pve-backup-server-dockerfiles/pull/15. You might apply this patch yourself and recompile.

**Comment by fila612** [comment]
Thanks for the tip, unfortunately my knowledge is not sufficient for this.
Will there be this patch in your image later?

**Comment by ayufan** [comment]
I would prefer if this patch is being sent upstream. This would be best. If
not accepted I might adapt that, but this is some additional maintenance
burden :(

**Comment by fila612** [comment]
understand, so I'm not able to do anything (sorry)
thanks for your quick help, should this issue be closed or it is better to leave it open until the handling regarding the patch is decided (upstream or adaption)?

**Comment by ayufan** [comment]
Leave it for now.

**Comment by pandada8** [comment]
I came across the same problem today on a ubuntu system with kernel 5.4.0-88-generic.
It can be solved by creating tmpfs mountpoint at `/run`

following docker-compose file can be an example
```
version: '2.1'

services:
  pbs:
    image: ayufan/proxmox-backup-server:latest
    network_mode: host
    mem_limit: 2G
    volumes:
      - /mnt/datastore/backup/pbs:/backups
      - ./etc:/etc/proxmox-backup
      - ./logs:/var/log/proxmox-backup
      - ./lib:/var/lib/proxmox-backup
    tmpfs:
      - /run
    restart: unless-stopped
    stop_signal: SIGHUP
```

I also have a Synology NAS and I tried the above docker-compose config. It runs just fine.

**Comment by fila612** [comment]
hm, strange... I had also created the volumes as tmpfs, what is the difference between yours and mines?
See screenshots above, running "df -h" displays tmpfs.....

**Comment by ayufan** [comment]
The need for `tmpfs` is documented in here:
- https://github.com/ayufan/pve-backup-server-dockerfiles#changelog
- https://github.com/ayufan/pve-backup-server-dockerfiles/blob/master/docker-compose.yml#L13

**Comment by fila612** [comment]
Thanks @pandada8 for the hint of the Mountpoint "/run"

that was the issue why its not working on my "Synology-Docker-Portainer" machine....:)
Point is: I had created the container completely via Portainer, but the Mountpoint "/run" cannon be created in the Portainer GUI, or maybe its possible, but I don't know how to do it.

nevertheless, if I use Portainer stack (=docker compose) the PBS is working on my Synology!!! 😄 

if someone are interested to my Portainer Stack content:
HINT:
the paths have to be validated by your own environment. i hat created following folders on my HOST-System
/volume1/Sicherung/Backups/PBS2
/volume1/docker/PBS2/etc
/volume1/docker/PBS2/log
/volume1/docker/PBS2/lib

`services:
  pbs:
    image: ayufan/proxmox-backup-server:latest
    network_mode: "bridge"
    ports:
      - "8007:8007"
    volumes:
      - backups:/backups
      - pbs_etc:/etc/proxmox-backup
      - pbs_log:/var/log/proxmox-backup
      - pbs_lib:/var/lib/proxmox-backup
    tmpfs:
      - /run
    restart: unless-stopped
    stop_signal: SIGHUP
    environment:
      TZ: Europe/Berlin
    devices:
      - /dev/sda
      - /dev/sdb
    cap_add:
      - SYS_RAWIO
volumes:
  backups:
    driver: local
    driver_opts:
      type: tmpfs
      o: bind
      device: /volume1/Sicherung/Backups/PBS2
  pbs_etc:
    driver: local
    driver_opts:
      type: tmpfs
      o: bind
      device: /volume1/docker/PBS2/etc
  pbs_log:
    driver: local
    driver_opts:
      type: tmpfs
      o: bind
      device: /volume1/docker/PBS2/log
  pbs_lib:
    driver: local
    driver_opts:
      type: tmpfs
      o: bind
      device: /volume1/docker/PBS2/lib`

**Comment by ayufan** [comment]
Yes, you need to pre-create paths.

**Comment by fila612** [comment]
from my side issue can be closed.
solution: Portainer-stack or docker compose instead of Portainer-GUI ;)

**Comment by ayufan** [comment]
@fila612 

Maybe all those details (about tmpfs and pre-create) we could add to README for next generation? :)

**Comment by SAOPP** [comment]
Hi!

I try to replace my own pbs 1x container with your. And as I see faced with kernel trouble... I run it on my openmediavault server, with current `kernel 4.19.0-0.bpo.9-amd64`, and in logs of container I get:
`Error: mkstemp "/run/proxmox-backup/proxy.tmp_XXXXXX" failed: ENOENT: No such file or directory`
And very shot time after my credentials is active, I mean very shot time before pbs re-ask to sig-in, not sure if it affialted with kernel and tmpfs `/run`, any suggestion? Thanks.

**Comment by SAOPP** [comment]
Btw, here os my stack:

```
volumes:
  pbs_etc:
    driver: local
  pbs_logs:
    driver: local
  pbs_lib:
    driver: local

  pbs:
    image: ayufan/proxmox-backup-server:latest
    container_name: proxmox-backup-server
    hostname: proxmox-backup-server
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sdd
    mem_limit: 2G
    networks:
      - omv
    environment:
      - TZ=Europe/Kiev
    volumes:
      - pbs_etc:/etc/proxmox-backup
      - pbs_logs:/var/log/proxmox-backup
      - pbs_lib:/var/lib/proxmox-backup
      - /sharedfolders/proxmox-backup:/storage
    tmpfs:
      - /run
    ports:
      - 8007:8007
    restart: unless-stopped
    stop_signal: SIGHUP
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
```
