### ISSUE TITLE
New setup won't start on Portainer

### ISSUE THREAD

**Issue by ShiftyMcCool** [ayufan/pve-backup-server-dockerfiles#44]
I initially made this comment on another issue before I realized it wasn't exactly the same.

I set up a new stack in Portainer with the details below and the container log showed the copy of default files and they appear on my mounted volume so that seems good. However, despite  dropping the stack and redeploying (once with v2.4.1) I get the same output:

```
PROXY: Starting...
rm: cannot remove '/etc/proxmox-backup/.*.lck': No such file or directory
rm: cannot remove '/etc/proxmox-backup/*.lock': No such file or directory
/etc/proxmox-backup is a mountpoint
/var/lib/proxmox-backup is a mountpoint
/var/log/proxmox-backup is a mountpoint
/run is a mountpoint
API: Starting...
```

I've let it sit like this for over 30 minutes without any movement. I'm guessing I'm doing something wrong, any ideas?

<img width="708" alt="image" src="https://github.com/ayufan/pve-backup-server-dockerfiles/assets/1320624/b3e341a8-b285-4f92-8ba1-ffd71755feb4">

docker-compose.yml:
```
version: '2.1'

services:
  proxmox-backup:
    image: ayufan/proxmox-backup-server:latest
    network_mode: host
    mem_limit: 2G
    volumes:
      - backups:/backups
      - pbs_etc:/etc/proxmox-backup
      - pbs_logs:/var/log/proxmox-backup
      - pbs_lib:/var/lib/proxmox-backup
    environment:
      TZ: America/Detroit
    tmpfs:
      - /run
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/mmcblk0
      - /dev/sda
    restart: unless-stopped
    stop_signal: SIGHUP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxmox-http.rule=Host(`proxmox.it-clowd`)"
      - "traefik.http.routers.proxmox-http.entrypoints=web"
      - "traefik.http.routers.proxmox-https.rule=Host(`proxmox.it-clowd`)"
      - "traefik.http.routers.proxmox-https.entrypoints=websecure"
      - "traefik.http.routers.proxmox-https.tls.certresolver=basic"
      - "traefik.http.services.proxmox-service.loadbalancer.server.port=8007"

volumes:
  backups:
    driver: local
    driver_opts:
      type: ''
      o: bind
      device: /media/data/proxmox/backups
  pbs_etc:
    driver: local
    driver_opts:
      type: ''
      o: bind
      device: /media/data/proxmox/etc
  pbs_logs:
    driver: local
    driver_opts:
      type: ''
      o: bind
      device: /media/data/proxmox/logs
  pbs_lib:
    driver: local
    driver_opts:
      type: ''
      o: bind
      device: /media/data/proxmox/lib
```

Let me know if you need any other details
Thanks!
