### ISSUE TITLE
Does it make sense to update the container with watchtower, or is it even dangerous?

### ISSUE THREAD

**Issue by Mitch187** [ayufan/pve-backup-server-dockerfiles#62]
Hi,

I know I'm in the issue area here. But I would still like to ask the question. I would be very happy if you could answer my question anyway. You can close the issue immediately afterwards.

I use Watchtower to update all containers on the fly and am very happy with it:
https://containrrr.dev/watchtower/

However, I'm not sure about your Proxmox Backup Server container. Here is my complete docker-compose:
```
services:
  pbs:
    image: ayufan/proxmox-backup-server:latest
    container_name: PBS
    hostname: proxmox-backup-server
    network_mode: bridge
    environment:
      - TZ=Europe/Berlin
    volumes:
      - backups:/backups
      - etc:/etc/proxmox-backup
      - logs:/var/log/proxmox-backup
      - lib:/var/lib/proxmox-backup
    tmpfs:
      - /run      
    ports:
      - 8007:8007
    restart: always

volumes:
  backups:
  etc:
  logs:
  lib:
```

I.e. if you have a new release as Docker, it should download the image directly and start the container again. I just have the feeling that this update path does not make sense, since e.g. etc. and also backup files must match the corresponding server, right? Or can I quickly break my PBS and should I rather perform the PBS version by deleting the entire container and creating a new initial backup of my machines?

Greetings,
Mitch

Translated with DeepL.com (free version)
