### ISSUE TITLE
Feature Request: Support for Additional Storage via Docker Compose

### ISSUE THREAD

**Issue by n3roGit** [ayufan/pve-backup-server-dockerfiles#63]
Hello everyone,

I would appreciate the ability to mount additional storage through the Docker Compose configuration. Specifically, it would be helpful if one could integrate the Hetzner Storage Box, allowing a portion of the data to be synchronized directly to it.

The Hetzner Storage Box supports the following protocols:

SFTP
rsync
SMB/CIFS
FTP/FTPS
This functionality would enable a more flexible and scalable backup strategy.
Thank you for considering this request!

**Comment by adrianipopescu** [comment]
you're not wrong, but it's better to support it directly

**Comment by ayufan** [comment]
@n3roGit You are good to mount whatever you need via docker-compose.

```yaml
services:
  pbs:
    volumes:
      - smb_backups:/smb_backups

volumes:
  smb_backups:
    driver: local
    driver_opts:
      type: cifs
      o: username=XXX,password=YY,uid=34,gid=34,vers=3.0,noexec
      device: "//IP/PATH"
```

Example. You have to use IP, as hostname does not work with docker-compose.
