### ISSUE TITLE
Can't use USB disks for DataStore

### ISSUE THREAD

**Issue by appscaptain** [ayufan/pve-backup-server-dockerfiles#71]
Awesome image! Would love to get this running on my Synology! I have created a Docker container from this image on a Synology DS218+ running DSM 7.2.1 and I want to back up to a USB disk. I have formatted the USB disk as ext4. It shows up under Storage / Disks in Proxmox but I can't select it when I try to create a DataStore or a directory. Also I can't wipe the disk from Proxmox (it never finishes) . I can format it just fine from the console manually. I have tried multiple USB enclosures. And the disk is all blank.

Any ideas? Here are some screenshots:

Disks: https://share.zight.com/eDupjqZd

Can't add directories :
https://share.zight.com/bLu2AENm

Can't add DataStore:
https://share.zight.com/JruY42QD

This is my docker-compose.yml:
```
version: '2.1'

services:
  pbs:
    image: ayufan/proxmox-backup-server:${TAG:-latest}
    ports:
      - 8007:8007
    mem_limit: 2G
    volumes:
      - /volume1/docker/pbs/etc:/etc/proxmox-backup
      - /volume1/docker/pbs/logs:/var/log/proxmox-backup
      - /volume1/docker/pbs/lib:/var/lib/proxmox-backup
      - /volume1/docker/pbs:/mnt/PromoxBackup
    tmpfs:
      - /run
    cap_add: # smartctl support
      - SYS_RAWIO
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdr:/dev/sdr
    restart: unless-stopped
    stop_signal: SIGHUP
```

The external disk is /dev/sdr.

Anyone has some ideas on how to fix this?
